POST localhost:8080/api/timetable/image/6days?horizontal
Content-Type: application/json


[
    {
        "disciplines": [
            {
                "time": "8:00-9:30",
                "name": "Разговоры о важном,",
                "teacherName": "Фомченко Ж.А.",
                "audienceId": "18",
                "subgroup": 0,
                "type": "none",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "9:40-11:10",
                "name": "Дисциплина по выбору \"Основы программирования роботов\"",
                "teacherName": "Голодов Е.А.",
                "audienceId": "21",
                "subgroup": 0,
                "type": "lab",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "9:40-11:10",
                "name": "Дисциплина по выбору \"Проектирование пользовательских интерфейсов\"",
                "teacherName": "Лапшин Н.А.",
                "audienceId": "23а",
                "subgroup": 0,
                "type": "lec",
                "groupName": "ВМ-ИВТ-2-1"
            }
        ],
        "date": "18.09.2023",
        "groupName": "ВМ-ИВТ-2-1"
    },
    {
        "disciplines": [
            {
                "time": "8:00-9:30",
                "name": "Физика",
                "teacherName": "Шермадина Н.А.",
                "audienceId": "14а",
                "subgroup": 0,
                "type": "lec",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "9:40-11:10",
                "name": "Электротехника",
                "teacherName": "Хорошилов М.М.",
                "audienceId": "23в",
                "subgroup": 0,
                "type": "lec",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "11:40-13:10",
                "name": "Дисциплина по выбору \"Использование интернет-ресурсов при решении задач профессиональной деятельности\"",
                "teacherName": "Лоба И.С.",
                "audienceId": "23а",
                "subgroup": 0,
                "type": "lab",
                "groupName": "ВМ-ИВТ-2-1"
            }
        ],
        "date": "19.09.2023",
        "groupName": "ВМ-ИВТ-2-1"
    },
    {
        "disciplines": [
            {
                "time": "8:00-9:30",
                "name": "Автоматизированные системы создания и сопровождения информационных систем",
                "teacherName": "Лапшин Н.А.",
                "audienceId": "9",
                "subgroup": 2,
                "type": "lab",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "9:40-11:10",
                "name": "Элективная дисциплина по физической культуре и спорту. Общая физическая подготовка.",
                "teacherName": "Закарян Г.З.",
                "audienceId": "Спортзал ФОК",
                "subgroup": 0,
                "type": "prac",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "11:40-13:10",
                "name": "Дисциплина по выбору \"Использование интернет-ресурсов при решении задач профессиональной деятельности\"",
                "teacherName": "Лоба И.С.",
                "audienceId": "23а",
                "subgroup": 0,
                "type": "lab",
                "groupName": "ВМ-ИВТ-2-1"
            }
        ],
        "date": "20.09.2023",
        "groupName": "ВМ-ИВТ-2-1"
    },
    {
        "disciplines": [
            {
                "time": "8:00-9:30",
                "name": "Физика",
                "teacherName": "Шермадина Н.А.",
                "audienceId": "14а",
                "subgroup": 0,
                "type": "prac",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "9:40-11:10",
                "name": "Иностранный язык",
                "teacherName": "Таткало Н.И.",
                "audienceId": "12",
                "subgroup": 2,
                "type": "lab",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "11:40-13:10",
                "name": "Дисциплина по выбору \"Проектирование пользовательских интерфейсов\"",
                "teacherName": "Лапшин Н.А.",
                "audienceId": "23а",
                "subgroup": 0,
                "type": "lab",
                "groupName": "ВМ-ИВТ-2-1"
            }
        ],
        "date": "21.09.2023",
        "groupName": "ВМ-ИВТ-2-1"
    },
    {
        "disciplines": [
            {
                "time": "8:00-9:30",
                "name": "Элективная дисциплина по физической культуре и спорту. Общая физическая подготовка.",
                "teacherName": "Закарян Г.З.",
                "audienceId": "Спортзал ФОК",
                "subgroup": 0,
                "type": "prac",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "9:40-11:10",
                "name": "Дисциплина по выбору \"Основы программирования роботов\"",
                "teacherName": "Голодов Е.А.",
                "audienceId": "21",
                "subgroup": 0,
                "type": "lab",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "11:40-13:10",
                "name": "Иностранный язык",
                "teacherName": "Таткало Н.И.",
                "audienceId": "12",
                "subgroup": 2,
                "type": "lab",
                "groupName": "ВМ-ИВТ-2-1"
            }
        ],
        "date": "22.09.2023",
        "groupName": "ВМ-ИВТ-2-1"
    },
    {
        "disciplines": [
            {
                "time": "8:00-9:30",
                "name": "Автоматизированные системы создания и сопровождения информационных систем",
                "teacherName": "Лапшин Н.А.",
                "audienceId": "21",
                "subgroup": 2,
                "type": "lab",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "9:40-11:10",
                "name": "Физика",
                "teacherName": "Шермадина Н.А.",
                "audienceId": "14а",
                "subgroup": 0,
                "type": "prac",
                "groupName": "ВМ-ИВТ-2-1"
            },
            {
                "time": "11:40-13:10",
                "name": "Электротехника",
                "teacherName": "Хорошилов М.М.",
                "audienceId": "14а",
                "subgroup": 0,
                "type": "lec",
                "groupName": "ВМ-ИВТ-2-1"
            }
        ],
        "date": "23.09.2023",
        "groupName": "ВМ-ИВТ-2-1"
    }
]