POST localhost:8080/api/timetable/image/day?horizontal
Content-Type: application/json


{
  "disciplines": [
    {
      "time": "8:00-9:30",
      "name": "Автоматизированные системы создания и сопровождения информационных систем",
      "teacherName": "Лесная Е.Н.",
      "audienceId": "12",
      "subgroup": 1,
      "type": "lab",
      "groupName": "ВМ-ИВТ-2-1"
    },
    {
      "time": "8:00-9:30",
      "name": "Автоматизированные системы создания и сопровождения информационных систем",
      "teacherName": "Лапшин Н.А.",
      "audienceId": "9",
      "subgroup": 2,
      "type": "lab",
      "groupName": "ВМ-ИВТ-2-1"
    },
    {
      "time": "9:40-11:10",
      "name": "Элективная дисциплина по физической культуре и спорту. Общая физическая подготовка.",
      "teacherName": "Закарян Г.З.",
      "audienceId": "Спортзал ФОК",
      "subgroup": 0,
      "type": "prac",
      "groupName": "ВМ-ИВТ-2-1"
    },
    {
      "time": "11:40-13:10",
      "name": "Дисциплина по выбору \"Использование интернет-ресурсов при решении задач профессиональной деятельности\"",
      "teacherName": "Лоба И.С.",
      "audienceId": "23а",
      "subgroup": 0,
      "type": "lab",
      "groupName": "ВМ-ИВТ-2-1"
    },
    {
      "time": "11:40-13:10",
      "name": "Дисциплина по выбору \"Управление Интернет-контентом\"",
      "teacherName": "Николаева Л.Г.",
      "audienceId": "13",
      "subgroup": 0,
      "type": "lab",
      "groupName": "ВМ-ИВТ-2-1"
    }
  ],
  "date": "20.09.2023",
  "groupName": "ВМ-ИВТ-2-1"
}