POST localhost:8080/api/timetable/image/discipline
Content-Type: application/json

[
  {
    "time": "8:00-9:30",
    "name": "Дисциплина по выбору Использование интернет-ресурсов при решении задач профессиональной деятельности",
    "teacherName": "Лесная Е.Н.",
    "audienceId": "12",
    "subgroup": 1,
    "type": "prac",
    "groupName": "ВМ-ИВТ-2-1"
  }
]